// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("index.html", "RDS Agri - Home", "Welcome   About Us RDS Agri  Pty  Ltd is a South African agricultural supply company focused on delivering reliable and affordable fertilizer solutions to farmers and agribusinesses We partner directly with reputable international manufacturers to source high-quality agricultural inputs, ensuring consistent product performance and dependable supply  Our Business RDS Agri specializes in the import and distribution of agricultural-grade urea  46% N  — one of the most widely used nitrogen fertilizers in crop production Our goal is to build a transparent and efficient supply chain that connects farmers with global producers at competitive prices As the business grows, RDS Agri plans to expand into NPK blends, phosphates, and soil nutrition products, strengthening its role as a complete fertilizer solutions provider  Vision To connect African farmers with world-class fertilizer products, empowering sustainable growth through affordable and effective plant nutrition    To be a trusted partner to the agricultural community by providing high-quality fertilizers, dependable logistics, and transparent business practices that support real productivity on the ground  •Commercial and emerging farmers •Agricultural cooperatives •Input retailers and wholesalers •Contract growers and agribusinesses  Mission Who We Serve Why Choose RDS AGRI •Direct Import Advantage •Reliable Quality •Customer-Focused •Growth-Oriented •Competitively priced  RDS AGRI Nourishing the soil that feeds our nation   Registration Number                 2025 / 699407 / 07 SOCIAL MEDIA  QUICK LINKS   ", "");
   this[database_length++] = new SearchPage("product.html", "RDS Agri - Products", "Products  Urea     Urea is a popular and dependable nitrogen fertilizer used by farmers to help crops grow strong and green It provides a high amount of nitrogen, which is essential for healthy leaf growth and better yields Urea is easy to handle, dissolves quickly in the soil, and works well on many types of crops When applied at the right time and rate, it helps improve soil fertility and supports steady, productive crop growth throughout the season  CAN   Calcium Ammonium Nitrate  CAN  27% N is a reliable nitrogen fertilizer that gives crops a quick and steady nutrient boost It contains both ammonium and nitrate nitrogen, so plants can take it up fast and keep feeding over time The added calcium helps improve soil structure and supports strong, healthy crop growth CAN is easy to spread, works well in most soil types, and is especially useful for top-dressing cereals, maize, and pasture  AN  Ammonium Nitrate  33-34% N     Ammonium Nitrate  AN  33–34% N is a high-nitrogen fertilizer that delivers fast and reliable nutrition to crops It contains both nitrate and ammonium nitrogen, giving plants an immediate boost while also providing sustained feeding as the crop grows AN works well in cooler conditions, spreads evenly, and is especially effective for cereals, grasses, and pasture When used correctly, it helps drive strong growth and improved yields  Compound C   Compound C is a granular NPK fertilizer designed for basal application in maize, wheat, barley, sorghum, and other cereal crops Its formulation delivers a strong nutrient foundation during early crop development, promoting vigorous root growth, healthy shoots, and improved yield potential  Compound D     Compound D is a granular NPK fertilizer designed for basal application at planting It delivers a balanced nutrient mix tailored for maize, wheat, sugar beans, and other field crops, especially those tolerant to chlorine Its formulation promotes early crop establishment and long-term productivity  DAP   DAP is a premium granular fertilizer offering a high concentration of phosphorus  46%  and nitrogen  18% , making it ideal for basal application across a wide range of crops It’s especially effective in promoting strong root development and early plant vigor, making it a go-to choice for farmers during planting season  RDS AGRI Nourishing the soil that feeds our nation   Registration Number                 2025 / 699407 / 07 SOCIAL MEDIA  QUICK LINKS   ", "");
   this[database_length++] = new SearchPage("contact.html", "RDS Agri - Contact", "Contact Us  Whether you're a farmer, distributor, or industry partner, we're here to grow together  in the spirit of Ubuntu Contact us for product inquiries, bulk orders, compliance support, or just to start a conversation about how we can work together Email revash@rdsagri.co.za Phone +27 72 183 1041 SOCIAL MEDIA  QUICK LINKS  RDS AGRI Nourishing the soil that feeds our nation   Registration Number                 2025 / 699407 / 07 CONTACT FORM  ", "");
   this[database_length++] = new SearchPage("about.html", "RDS Agri - About", "About Us  RDS Agri -Feeding our Food RDS Agri is a dedicated agricultural distribution company focused on supplying high-quality agricultural inputs to farmers and agri-businesses across South Africa  We understand that agriculture depends on reliability, timing, and trust That’s why we work with reputable manufacturers and suppliers to ensure that every product we distribute meets strict quality and regulatory standards Our mission is simple  deliver dependable solutions that support productivity, sustainability, and long-term growth within the agricultural sector  At RDS Agri, we are committed to building strong partnerships and contributing meaningfully to the value chain that sustains our nation’s food supply              Revash Singh   CEO  RDS Agri was founded with a clear purpose, to strengthen agriculture by providing reliable access to quality inputs and building long-term, trust-based relationships within the industry  As a chemical engineer, I approach this business with a systems-driven mindset focused on efficiency, structure, and practical problem-solving Agriculture is a sector that demands precision and consistency, and RDS Agri is built on those principles  Our goal is not simply to distribute products, but to become a dependable partner to farmers and enterprises in the sector As we grow, our commitment remains rooted in professionalism, integrity, humility, and service  Agriculture feeds our communities, our economy, and our future At RDS Agri, we are proud to play our part  Thank you for being part of the RDS Agri journey  RDS AGRI Nourishing the soil that feeds our nation   Registration Number                 2025 / 699407 / 07 SOCIAL MEDIA  QUICK LINKS   ", "");
   return this;
}
